name: Checks

on:
  push:
    tags-ignore:
      - 'v*'
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint code
        run: |
          npm install
          npm run check

    steps:
      - uses: actions/checkout@v2
      - name: Lint code
        run: |
          npm run lint

  # test:
  #   needs: lint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run tests
  #       run: npm run test